// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ActivateRoute(routeID: string, profileID: string): $CancellablePromise<void> {
    return $Call.ByID(23255109, routeID, profileID);
}

export function AutostartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(4206343947);
}

export function CodexRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(565461819);
}

export function CreateModel(providerID: string, id: string, name: string): $CancellablePromise<$models.ModelDTO> {
    return $Call.ByID(244308170, providerID, id, name);
}

export function CreateProfile(id: string, name: string): $CancellablePromise<$models.ProfileDTO> {
    return $Call.ByID(2207031774, id, name);
}

export function CreateProvider(id: string, name: string, baseURL: string, authRef: string): $CancellablePromise<$models.ProviderDTO> {
    return $Call.ByID(292345612, id, name, baseURL, authRef);
}

export function CreateRoute(id: string, name: string, providerID: string, modelID: string): $CancellablePromise<$models.RouteDTO> {
    return $Call.ByID(3913029230, id, name, providerID, modelID);
}

export function DeleteModel(providerID: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(4105665551, providerID, id);
}

export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(495927951, id);
}

export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(3613641423, id);
}

export function DeleteRoute(id: string): $CancellablePromise<void> {
    return $Call.ByID(2675161171, id);
}

export function ListModels(): $CancellablePromise<$models.ModelDTO[] | null> {
    return $Call.ByID(3339455847);
}

export function ListModelsByProvider(providerID: string): $CancellablePromise<$models.ModelDTO[] | null> {
    return $Call.ByID(2850412303, providerID);
}

export function ListProfiles(): $CancellablePromise<$models.ProfileDTO[] | null> {
    return $Call.ByID(3182828123);
}

export function ListProviders(): $CancellablePromise<$models.ProviderDTO[] | null> {
    return $Call.ByID(967504745);
}

export function ListRoutes(): $CancellablePromise<$models.RouteDTO[] | null> {
    return $Call.ByID(2210676955);
}

export function RestoreCodexConfig(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(1724632070, profileID);
}

export function SaveModel(item: $models.ModelDTO): $CancellablePromise<void> {
    return $Call.ByID(2169819981, item);
}

export function SaveProfile(item: $models.ProfileDTO): $CancellablePromise<void> {
    return $Call.ByID(3160292805, item);
}

export function SaveProvider(item: $models.ProviderDTO): $CancellablePromise<void> {
    return $Call.ByID(2548824829, item);
}

export function SaveRoute(item: $models.RouteDTO): $CancellablePromise<void> {
    return $Call.ByID(1033275885, item);
}

export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1529005708, enabled);
}

export function StartCodex(): $CancellablePromise<void> {
    return $Call.ByID(56129242);
}

export function TestProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(1724053524, id);
}

export function TestProviderModel(providerID: string, modelID: string): $CancellablePromise<void> {
    return $Call.ByID(1289429633, providerID, modelID);
}
