// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ActivateRoute(routeID: string, profileID: string): $CancellablePromise<void> {
    return $Call.ByID(873382751, routeID, profileID);
}

export function AutostartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(200679149);
}

/**
 * CheckProviderHealth performs an explicit, read-only connectivity check. It
 * is never called during list/reload and it returns only a safe error code.
 */
export function CheckProviderHealth(id: string): $CancellablePromise<$models.ProviderHealthDTO> {
    return $Call.ByID(3751159922, id);
}

export function CodexRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3120239309);
}

export function CreateModel(providerID: string, id: string, name: string): $CancellablePromise<$models.ModelDTO> {
    return $Call.ByID(2667702664, providerID, id, name);
}

export function CreateProfile(id: string, name: string): $CancellablePromise<$models.ProfileDTO> {
    return $Call.ByID(4226225588, id, name);
}

export function CreateProvider(id: string, name: string, baseURL: string, authRef: string): $CancellablePromise<$models.ProviderDTO> {
    return $Call.ByID(3505045306, id, name, baseURL, authRef);
}

export function CreateRoute(id: string, name: string, providerID: string, modelID: string): $CancellablePromise<$models.RouteDTO> {
    return $Call.ByID(3967486520, id, name, providerID, modelID);
}

export function DeleteModel(providerID: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(1717413909, providerID, id);
}

export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(1821354509, id);
}

export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(3093367877, id);
}

export function DeleteRoute(id: string): $CancellablePromise<void> {
    return $Call.ByID(217495733, id);
}

/**
 * ExportWorkspace returns a credential-safe JSON snapshot. Header/query
 * values are deliberately omitted because they may contain secrets; auth_ref
 * is retained only when it is a valid environment/Credential Manager reference.
 */
export function ExportWorkspace(): $CancellablePromise<string> {
    return $Call.ByID(3459772146);
}

/**
 * ImportCodexConfig explicitly snapshots the current config.toml into a new
 * profile. auth.json is never copied or modified by this operation.
 */
export function ImportCodexConfig(id: string, name: string): $CancellablePromise<$models.ProfileDTO> {
    return $Call.ByID(1150193431, id, name);
}

/**
 * ImportWorkspace applies a previously previewed snapshot only when it is
 * valid and conflict-free. The importer appends resources atomically and never
 * overwrites existing IDs or touches auth.json.
 */
export function ImportWorkspace(payload: string): $CancellablePromise<$models.WorkspaceImportPreviewDTO> {
    return $Call.ByID(2123820419, payload);
}

/**
 * InspectCodexConfig is read-only. Importing a detected config is deliberately
 * a separate user action and this method never writes config.toml or auth.json.
 */
export function InspectCodexConfig(): $CancellablePromise<$models.CodexConfigStatusDTO> {
    return $Call.ByID(3877297554);
}

export function ListModels(): $CancellablePromise<$models.ModelDTO[] | null> {
    return $Call.ByID(2613219817);
}

export function ListModelsByProvider(providerID: string): $CancellablePromise<$models.ModelDTO[] | null> {
    return $Call.ByID(3642070005, providerID);
}

export function ListProfiles(): $CancellablePromise<$models.ProfileDTO[] | null> {
    return $Call.ByID(565344365);
}

/**
 * ListProviderPresets returns read-only templates. They contain no credential
 * values and selecting one never writes state until CreateProvider is called.
 */
export function ListProviderPresets(): $CancellablePromise<$models.ProviderPresetDTO[] | null> {
    return $Call.ByID(1615070446);
}

export function ListProviders(): $CancellablePromise<$models.ProviderDTO[] | null> {
    return $Call.ByID(3646985203);
}

export function ListRoutes(): $CancellablePromise<$models.RouteDTO[] | null> {
    return $Call.ByID(603517273);
}

/**
 * PreviewWorkspaceImport validates an exported snapshot without mutating any
 * state. Unknown fields are rejected so headers, query parameters, auth.json
 * content, and future secret-bearing fields cannot sneak into an import flow.
 */
export function PreviewWorkspaceImport(payload: string): $CancellablePromise<$models.WorkspaceImportPreviewDTO> {
    return $Call.ByID(2090375363, payload);
}

export function RestoreCodexConfig(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(901113128, profileID);
}

export function SaveModel(item: $models.ModelDTO): $CancellablePromise<void> {
    return $Call.ByID(1448447267, item);
}

export function SaveProfile(item: $models.ProfileDTO): $CancellablePromise<void> {
    return $Call.ByID(2243619131, item);
}

export function SaveProvider(item: $models.ProviderDTO): $CancellablePromise<void> {
    return $Call.ByID(3302885907, item);
}

export function SaveRoute(item: $models.RouteDTO): $CancellablePromise<void> {
    return $Call.ByID(790395727, item);
}

export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1045741050, enabled);
}

export function StartCodex(): $CancellablePromise<void> {
    return $Call.ByID(3525466424);
}

export function SyncProviderModels(providerID: string): $CancellablePromise<$models.ModelDTO[] | null> {
    return $Call.ByID(134197607, providerID);
}

export function TestProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(3983325534, id);
}

export function TestProviderModel(providerID: string, modelID: string): $CancellablePromise<void> {
    return $Call.ByID(3034640651, providerID, modelID);
}
