// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ModelDTO {
    "provider_id": string;
    "id": string;
    "name": string;
    "enabled": boolean;
}

export interface ProfileDTO {
    "id": string;
    "name": string;
    "route_id"?: string;
    "config_path"?: string;
    "model_catalog_path"?: string;
}

export interface ProviderDTO {
    "id": string;
    "name": string;
    "base_url": string;
    "protocol": string;
    "auth_ref"?: string;
    "headers"?: { [_ in string]?: string } | null;
    "query_params"?: { [_ in string]?: string } | null;
}

export interface RouteDTO {
    "id": string;
    "name": string;
    "platform_id": string;
    "provider_id": string;
    "model_id": string;
    "restart_on_activate": boolean;
    "default": boolean;
}
